// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using resume_app.Models;

namespace resume_app.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20191116191233_NewsFeed")]
    partial class NewsFeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("resume_app.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<string>("GithubLink");

                    b.Property<string>("LongDesc");

                    b.Property<string>("PictureLink");

                    b.Property<string>("ShortDesc");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Technologies");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("resume_app.Models.Update", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("date");

                    b.Property<string>("details");

                    b.HasKey("ID");

                    b.ToTable("Updates");
                });
#pragma warning restore 612, 618
        }
    }
}
